use axum::{Router, routing::get, routing::post, routing::put, routing::delete, middleware as axum_mw};
use crate::api::handler::{user, node, website, docker, plugin, ws, operation_log, log, auth, web_server, settings, database, file, firewall};
use crate::api::types::AppState;
use crate::api::middleware;

pub fn create_router(state: AppState) -> Router {
    Router::new()
        .route("/health", get(|| async { "OK" }))
        .route("/api/auth/login", post(auth::login))
        .route("/api/auth/change-password", post(auth::change_password))
        .route("/api/users", get(user::list))
        .route("/api/users", post(user::create))
        .route("/api/users/:id", put(user::update))
        .route("/api/users/:id", delete(user::delete))
        .route("/api/nodes", get(node::list))
        .route("/api/nodes", post(node::create))
        .route("/api/nodes/:id", put(node::update))
        .route("/api/nodes/:id", delete(node::delete))
        .route("/api/websites", get(website::list))
        .route("/api/websites", post(website::create))
        .route("/api/websites/:id", get(website::get))
        .route("/api/websites/:id", put(website::update))
        .route("/api/websites/:id", delete(website::delete))
        .route("/api/docker/containers", get(docker::list))
        .route("/api/docker/containers/:id", get(docker::get))
        .route("/api/docker/containers/:id/start", post(docker::start))
        .route("/api/docker/containers/:id/stop", post(docker::stop))
        .route("/api/docker/containers/:id/restart", post(docker::restart))
        .route("/api/docker/containers/:id/remove", post(docker::remove))
        .route("/api/docker/containers/:id/logs", get(docker::logs))
        .route("/api/docker/containers/:id/stats", get(docker::stats))
        .route("/api/docker/images", get(docker::list_images))
        .route("/api/docker/images/:id/remove", post(docker::remove_image))
        .route("/api/docker/compose/deploy", post(docker::compose_deploy))
        .route("/api/docker/compose/:project_name/up", post(docker::compose_up))
        .route("/api/docker/compose/:project_name/down", post(docker::compose_down))
        // Plugin endpoints
        .route("/api/plugins", get(plugin::list_plugins))
        .route("/api/plugins", post(plugin::load_plugin))
        .route("/api/plugins/:id", get(plugin::get_plugin))
        .route("/api/plugins/:id", post(plugin::unload_plugin))
        .route("/api/plugins/:id/enable", post(plugin::enable_plugin))
        .route("/api/plugins/:id/disable", post(plugin::disable_plugin))
        .route("/api/plugins/:id/execute/:function", post(plugin::execute_plugin))
        .route("/api/plugins/:id/reload", post(plugin::reload_plugin))
        .route("/api/plugins/:id/metrics", get(plugin::get_plugin_metrics))
        .route("/api/plugins/:id/metrics", delete(plugin::reset_plugin_metrics))
        .route("/api/plugins/:id/settings", get(plugin::list_plugin_settings))
        .route("/api/plugins/:id/settings", post(plugin::set_plugin_setting))
        .route("/api/plugins/:id/settings/:key", get(plugin::get_plugin_setting))
        // Web server endpoints
        .route("/api/web-servers/engines", get(web_server::list_engines))
        .route("/api/web-servers", get(web_server::list))
        .route("/api/web-servers", post(web_server::create))
        .route("/api/web-servers/:id", get(web_server::get))
        .route("/api/web-servers/:id", put(web_server::update))
        .route("/api/web-servers/:id", delete(web_server::delete))
        .route("/api/web-servers/:id/start", post(web_server::start))
        .route("/api/web-servers/:id/stop", post(web_server::stop))
        .route("/api/web-servers/:id/restart", post(web_server::restart))
        .route("/api/web-servers/:id/reload", post(web_server::reload))
        .route("/api/web-servers/:id/configtest", post(web_server::config_test))
        .route("/api/web-servers/:id/config", get(web_server::get_config))
        .route("/api/web-servers/:id/config", post(web_server::update_config))
        // Settings
        .route("/api/settings", get(settings::list_settings))
        .route("/api/settings/:key", get(settings::get_setting))
        .route("/api/settings", put(settings::update_setting))
        // Database endpoints
        .route("/api/databases", get(database::list))
        .route("/api/databases/:id", get(database::get))
        .route("/api/databases/:id", delete(database::delete))
        .route("/api/databases/mysql/install", post(database::install_mysql))
        .route("/api/databases/redis/install", post(database::install_redis))
        .route("/api/databases/:id/start", post(database::start))
        .route("/api/databases/:id/stop", post(database::stop))
        .route("/api/databases/:id/restart", post(database::restart))
        .route("/api/databases/:id/status", get(database::check_status))
        .route("/api/databases/:id/databases", get(database::list_databases))
        .route("/api/databases/:id/databases", post(database::create_database))
        .route("/api/databases/:id/databases/:db_name", delete(database::drop_database))
        .route("/api/databases/:id/users", post(database::create_user))
        .route("/api/databases/:id/users/:username", delete(database::drop_user))
        .route("/api/databases/:id/uninstall", post(database::uninstall))
        // File manager endpoints
        .route("/api/files", get(file::list))
        .route("/api/files/read", get(file::read))
        .route("/api/files/write", post(file::write))
        .route("/api/files/create-file", post(file::create_file))
        .route("/api/files/create-dir", post(file::create_dir))
        .route("/api/files/delete", delete(file::delete))
        .route("/api/files/rename", post(file::rename))
        .route("/api/files/chmod", post(file::chmod))
        .route("/api/files/upload", post(file::upload))
        .route("/api/files/download", get(file::download))
        // Firewall endpoints
        .route("/api/firewall/rules", get(firewall::list))
        .route("/api/firewall/rules", post(firewall::create))
        .route("/api/firewall/rules/:id", get(firewall::get))
        .route("/api/firewall/rules/:id", put(firewall::update))
        .route("/api/firewall/rules/:id", delete(firewall::delete))
        .route("/api/firewall/rules/:id/toggle", post(firewall::toggle))
        .route("/api/firewall/apply", post(firewall::apply_all))
        .route("/api/firewall/status", get(firewall::get_status))
        .route("/api/firewall/enable", post(firewall::enable))
        .route("/api/firewall/disable", post(firewall::disable))
        .route("/api/firewall/reorder", post(firewall::reorder))
        // Logs
        .route("/api/operation-logs", get(operation_log::list))
        .route("/api/operation-logs/:id", delete(operation_log::delete))
        .route("/api/logs", get(log::list))
        .route("/api/logs/:id", delete(log::delete))
        .merge(ws::routes())
        .layer(axum_mw::from_fn_with_state(state.clone(), middleware::rbac_middleware))
        .with_state(state)
}
