server {
    listen {{ port }};
    server_name {{ domain }};

    root {{ root }};
    index index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    {% if ssl %}
    listen 443 ssl;
    ssl_certificate {{ ssl_cert }};
    ssl_certificate_key {{ ssl_key }};
    {% endif %}
}